### ISSUE TITLE
A new guard page for the stack cannot be created

### ISSUE THREAD

**Issue by valkyrienyanko** [QueenOfSquiggles/WhereTheDeadLie#1]
I get this popup when I try to open your game. Clicking the "OK" closes everything. No errors are logged when running Godot in `--verbose` mode. I did a quick web search and internet says I've run out of RAM but when I look at task manager, this is not the case. Maybe I need to allocate more RAM to Godot to open your game? I don't know how to do that.

![Capture](https://user-images.githubusercontent.com/6277739/215618673-5b392f51-04d3-413c-bd8a-90ab56b22816.PNG)

**Comment by QueenOfSquiggles** [comment]
Wow I'm really sorry I didn't see this until now! GitHub didn't give me a notification or anything!

So far there is some issue with the windows build that several people have been having. I'll be looking into this problem to see if I can solve it. Thanks a ton for submitting an issue!

**Comment by QueenOfSquiggles** [comment]
If you're at all interested, the issue on the godot engine repo is here: https://github.com/godotengine/godot/issues/72739

**Comment by QueenOfSquiggles** [comment]
I should probably mark this as closed. The main issue was solved with Godot 4b17, and the most recent build of the game is in working order. Apologies that it took so long for me to come back to this!

**Comment by valkyrienyanko** [comment]
Not sure where else to ask this.

I'm using Visual Studio 2022 to look at all your C# scripts.

And CodeLens is showing the references for stuff like classes.

![Capture](https://user-images.githubusercontent.com/6277739/219828615-2e094e2f-7b84-4601-8f52-470fa4a71b14.PNG)

So I can click on that and see wherever that class was used which is super duper helpful.

But CodeLens does not show this for fields or events. Only for properties. So I'm having a very hard time following where everything leads (especially events). I'm finding myself doing `Ctrl + F` searches just to see where it all goes.

So my question is does your IDE let you see references for fields / events? And if so what IDE are you using.

P.S. You're right Godot did fix the issue and I was able to play the game just fine.

**Comment by QueenOfSquiggles** [comment]
I personally use Visual Studio Code, mainly because it's pretty good for code analysis while still being flexible and running on Linux. I do see the ref count on fields and methods. It's a bit strange that the "flag ship" code editor doesn't have that. Possibly there's a setting to change? By default in VSCode it is enabled, but I can disable viewing ref counts if I like. 

Also probably interesting note, that you probably already know, Godot 4 switched from Reflection to Source Generation for C# code, which is why scripts for Godot need to be marked as partial. The source generated creates the hookups for signals to have C# events as well as all kinds of extra _sugar_. So a significant number of references are going to be from generated source files (I think 4 is the immediate number of references?)

Also if you do have any more questions, I'm **really bad** about checking my notifications on GitHub. But I do have a Mastodon account that I use pretty regularly. So if you ever wanna ask more, I'm @queenofsquiggles@indiepocalypse.social
